# Generated by Django 5.0.3 on 2024-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikedatails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='description',
        ),
        migrations.AddField(
            model_name='bike',
            name='isfavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
