# Generated by Django 5.0.3 on 2024-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikedatails', '0002_remove_bike_description_bike_isfavorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='rating',
            field=models.FloatField(),
        ),
    ]
