# Generated by Django 5.0.3 on 2024-03-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikedatails', '0003_alter_bike_location_alter_bike_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='isfavorite',
        ),
    ]
