# Generated by Django 5.0.3 on 2024-03-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikedatails', '0004_remove_bike_isfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='isfavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
