# Generated by Django 5.0.3 on 2024-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikedatails', '0005_bike_isfavorite_alter_bike_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
